spring:
  datasource:
    platform: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: postgres
    hikari:
      schema: public
    separator: ;
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true