spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: admin1
    hikari:
      schema: public
    separator: ;
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8081