package com.dvimer.auto.crm.hbm2java;
// Generated 23.09.2019 12:14:04 by Hibernate Tools 6.0.1-SNAPSHOT


import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Osago generated by hbm2java
 */
@Entity
@Table(name = "osago"
)
public class Osago implements java.io.Serializable {


    private Integer id;
    private Agent agent;
    private String kindClient;
    private String office;
    private Integer numberOffice;
    private String area;
    private Date creationDate;
    private Date startDate;
    private String firstName;
    private String lastName;
    private String patronomic;
    private String phoneNumber;
    private String inshuranceName;
    private String modelAuto;
    private String kindInsurance;
    private Integer baseRate;
    private BigDecimal price;
    private Integer sale;
    private BigDecimal priceWithSale;
    private Integer delivery;
    private BigDecimal totalAmount;
    private Integer kv;
    private BigDecimal kvAll;
    private Integer kvTotal;
    private boolean dk;
    private Integer adminSalary;
    private Integer ourSalasy;
    private Integer cashbox;
    private Integer broughtAll;

    public Osago() {
    }


    public Osago(Integer id) {
        this.id = id;
    }

    public Osago(Integer id, Agent agent, String kindClient, String office, Integer numberOffice, String area, Date creationDate, Date startDate, String firstName, String lastName, String patronomic, String phoneNumber, String inshuranceName, String modelAuto, String kindInsurance, Integer baseRate, BigDecimal price, Integer sale, BigDecimal priceWithSale, Integer delivery, BigDecimal totalAmount, Integer kv, BigDecimal kvAll, Integer kvTotal, boolean dk, Integer adminSalary, Integer ourSalasy, Integer cashbox, Integer broughtAll) {
        this.id = id;
        this.agent = agent;
        this.kindClient = kindClient;
        this.office = office;
        this.numberOffice = numberOffice;
        this.area = area;
        this.creationDate = creationDate;
        this.startDate = startDate;
        this.firstName = firstName;
        this.lastName = lastName;
        this.patronomic = patronomic;
        this.phoneNumber = phoneNumber;
        this.inshuranceName = inshuranceName;
        this.modelAuto = modelAuto;
        this.kindInsurance = kindInsurance;
        this.baseRate = baseRate;
        this.price = price;
        this.sale = sale;
        this.priceWithSale = priceWithSale;
        this.delivery = delivery;
        this.totalAmount = totalAmount;
        this.kv = kv;
        this.kvAll = kvAll;
        this.kvTotal = kvTotal;
        this.dk = dk;
        this.adminSalary = adminSalary;
        this.ourSalasy = ourSalasy;
        this.cashbox = cashbox;
        this.broughtAll = broughtAll;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @OneToOne (optional=false, cascade=CascadeType.ALL)
    @JoinColumn (name="agent")
    public Agent getAgent() {
        return this.agent;
    }

    public void setAgent(Agent agent) {
        this.agent = agent;
    }

    @Column(name = "kind_client", length = 100)
    public String getKindClient() {
        return kindClient;
    }

    public void setKindClient(String kindClient) {
        this.kindClient = kindClient;
    }

    @Column(name = "office", length = 100)
    public String getOffice() {
        return this.office;
    }

    public void setOffice(String office) {
        this.office = office;
    }


    @Column(name = "number_office", precision = 5, scale = 0)
    public Integer getNumberOffice() {
        return this.numberOffice;
    }

    public void setNumberOffice(Integer numberOffice) {
        this.numberOffice = numberOffice;
    }


    @Column(name = "area", length = 100)
    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    @Column(name = "creation_date", length = 13)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    @Column(name = "start_date", length = 13)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }


    @Column(name = "first_name", length = 100)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    @Column(name = "last_name", length = 100)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    @Column(name = "patronomic", length = 100)
    public String getPatronomic() {
        return this.patronomic;
    }

    public void setPatronomic(String patronomic) {
        this.patronomic = patronomic;
    }


    @Column(name = "phone_number")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name = "inshurance_name", length = 100)
    public String getInshuranceName() {
        return inshuranceName;
    }

    public void setInshuranceName(String inshuranceName) {
        this.inshuranceName = inshuranceName;
    }
    @Column(name = "model_auto", length = 100)
    public String getModelAuto() {
        return modelAuto;
    }

    public void setModelAuto(String modelAuto) {
        this.modelAuto = modelAuto;
    }

    @Column(name = "kind_insurance", length = 100)
    public String getKindInsurance() {
        return this.kindInsurance;
    }

    public void setKindInsurance(String kindInsurance) {
        this.kindInsurance = kindInsurance;
    }


    @Column(name = "base_rate", precision = 10, scale = 0)
    public Integer getBaseRate() {
        return this.baseRate;
    }

    public void setBaseRate(Integer baseRate) {
        this.baseRate = baseRate;
    }


    @Column(name = "price", precision = 10, scale = 0)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }


    @Column(name = "sale", precision = 3, scale = 0)
    public Integer getSale() {
        return this.sale;
    }

    public void setSale(Integer sale) {
        this.sale = sale;
    }
    @Column(name = "prica_with_sale", precision = 10, scale = 0)
    public BigDecimal getPriceWithSale() {
        return priceWithSale;
    }

    public void setPriceWithSale(BigDecimal priceWithSale) {
        this.priceWithSale = priceWithSale;
    }

    @Column(name = "delivery", precision = 20, scale = 0)
    public Integer getDelivery() {
        return this.delivery;
    }

    public void setDelivery(Integer delivery) {
        this.delivery = delivery;
    }


    @Column(name = "total_amount", precision = 20, scale = 0)
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }


    @Column(name = "kv", precision = 2, scale = 0)
    public Integer getKv() {
        return this.kv;
    }

    public void setKv(Integer kv) {
        this.kv = kv;
    }


    @Column(name = "kv_all", precision = 10, scale = 0)
    public BigDecimal getKvAll() {
        return this.kvAll;
    }

    public void setKvAll(BigDecimal kvAll) {
        this.kvAll = kvAll;
    }


    @Column(name = "kv_total", precision = 10, scale = 0)
    public Integer getKvTotal() {
        return this.kvTotal;
    }

    public void setKvTotal(Integer kvTotal) {
        this.kvTotal = kvTotal;
    }


    @Column(name = "dk")
    public boolean getDk() {
        return this.dk;
    }

    public void setDk(boolean dk) {
        this.dk = dk;
    }


    @Column(name = "admin_salary", precision = 10, scale = 0)
    public Integer getAdminSalary() {
        return this.adminSalary;
    }

    public void setAdminSalary(Integer adminSalary) {
        this.adminSalary = adminSalary;
    }


    @Column(name = "our_salasy", precision = 10, scale = 0)
    public Integer getOurSalasy() {
        return this.ourSalasy;
    }

    public void setOurSalasy(Integer ourSalasy) {
        this.ourSalasy = ourSalasy;
    }


    @Column(name = "cashbox", precision = 10, scale = 0)
    public Integer getCashbox() {
        return this.cashbox;
    }

    public void setCashbox(Integer cashbox) {
        this.cashbox = cashbox;
    }


    @Column(name = "brought_all", precision = 10, scale = 0)
    public Integer getBroughtAll() {
        return this.broughtAll;
    }

    public void setBroughtAll(Integer broughtAll) {
        this.broughtAll = broughtAll;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Osago osago = (Osago) o;
        return dk == osago.dk &&
                Objects.equals(id, osago.id) &&
                Objects.equals(agent, osago.agent) &&
                Objects.equals(kindClient, osago.kindClient) &&
                Objects.equals(office, osago.office) &&
                Objects.equals(numberOffice, osago.numberOffice) &&
                Objects.equals(area, osago.area) &&
                Objects.equals(creationDate, osago.creationDate) &&
                Objects.equals(startDate, osago.startDate) &&
                Objects.equals(firstName, osago.firstName) &&
                Objects.equals(lastName, osago.lastName) &&
                Objects.equals(patronomic, osago.patronomic) &&
                Objects.equals(phoneNumber, osago.phoneNumber) &&
                Objects.equals(inshuranceName, osago.inshuranceName) &&
                Objects.equals(modelAuto, osago.modelAuto) &&
                Objects.equals(kindInsurance, osago.kindInsurance) &&
                Objects.equals(baseRate, osago.baseRate) &&
                Objects.equals(price, osago.price) &&
                Objects.equals(sale, osago.sale) &&
                Objects.equals(priceWithSale, osago.priceWithSale) &&
                Objects.equals(delivery, osago.delivery) &&
                Objects.equals(totalAmount, osago.totalAmount) &&
                Objects.equals(kv, osago.kv) &&
                Objects.equals(kvAll, osago.kvAll) &&
                Objects.equals(kvTotal, osago.kvTotal) &&
                Objects.equals(adminSalary, osago.adminSalary) &&
                Objects.equals(ourSalasy, osago.ourSalasy) &&
                Objects.equals(cashbox, osago.cashbox) &&
                Objects.equals(broughtAll, osago.broughtAll);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, agent, kindClient, office, numberOffice, area, creationDate, startDate, firstName, lastName, patronomic, phoneNumber, inshuranceName, modelAuto, kindInsurance, baseRate, price, sale, priceWithSale, delivery, totalAmount, kv, kvAll, kvTotal, dk, adminSalary, ourSalasy, cashbox, broughtAll);
    }

    @Override
    public String toString() {
        return "Osago{" +
                "id=" + id +
                ", agent='" + agent + '\'' +
                ", kindClient='" + kindClient + '\'' +
                ", office='" + office + '\'' +
                ", numberOffice=" + numberOffice +
                ", area='" + area + '\'' +
                ", creationDate=" + creationDate +
                ", startDate=" + startDate +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", patronomic='" + patronomic + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", inshuranceName='" + inshuranceName + '\'' +
                ", modelAuto='" + modelAuto + '\'' +
                ", kindInsurance='" + kindInsurance + '\'' +
                ", baseRate=" + baseRate +
                ", price=" + price +
                ", sale=" + sale +
                ", priceWithSale=" + priceWithSale +
                ", delivery=" + delivery +
                ", totalAmount=" + totalAmount +
                ", kv=" + kv +
                ", kvAll=" + kvAll +
                ", kvTotal=" + kvTotal +
                ", dk=" + dk +
                ", adminSalary=" + adminSalary +
                ", ourSalasy=" + ourSalasy +
                ", cashbox=" + cashbox +
                ", broughtAll=" + broughtAll +
                '}';
    }
}


