package com.dvimer.auto.crm.hbm2java;
// Generated 23.09.2019 12:14:04 by Hibernate Tools 6.0.1-SNAPSHOT


import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Osago generated by hbm2java
 */
@Entity
@Table(name = "osago"
)
public class Osago implements java.io.Serializable {


    private Integer id;
    private String agent;
    private String office;
    private Integer numberOffice;
    private String area;
    private Date creationDate;
    private Date startDate;
    private String firstName;
    private String lastName;
    private String patronomic;
    private Integer phoneNumber;
    private String kindInsurance;
    private BigDecimal baseRate;
    private BigDecimal price;
    private BigDecimal sale;
    private BigDecimal delivery;
    private BigDecimal totalAmount;
    private BigDecimal kv;
    private BigDecimal kvAll;
    private BigDecimal kvTotal;
    private BigDecimal dk;
    private BigDecimal adminSalary;
    private BigDecimal ourSalasy;
    private BigDecimal cashbox;
    private BigDecimal broughtAll;
    private String other;

    public Osago() {
    }


    public Osago(Integer id) {
        this.id = id;
    }

    public Osago(Integer id, String agent, String office, Integer numberOffice, String area, Date creationDate, Date startDate, String firstName, String lastName, String patronomic, Integer phoneNumber, String kindInsurance, BigDecimal baseRate, BigDecimal price, BigDecimal sale, BigDecimal delivery, BigDecimal totalAmount, BigDecimal kv, BigDecimal kvAll, BigDecimal kvTotal, BigDecimal dk, BigDecimal adminSalary, BigDecimal ourSalasy, BigDecimal cashbox, BigDecimal broughtAll, String other) {
        this.id = id;
        this.agent = agent;
        this.office = office;
        this.numberOffice = numberOffice;
        this.area = area;
        this.creationDate = creationDate;
        this.startDate = startDate;
        this.firstName = firstName;
        this.lastName = lastName;
        this.patronomic = patronomic;
        this.phoneNumber = phoneNumber;
        this.kindInsurance = kindInsurance;
        this.baseRate = baseRate;
        this.price = price;
        this.sale = sale;
        this.delivery = delivery;
        this.totalAmount = totalAmount;
        this.kv = kv;
        this.kvAll = kvAll;
        this.kvTotal = kvTotal;
        this.dk = dk;
        this.adminSalary = adminSalary;
        this.ourSalasy = ourSalasy;
        this.cashbox = cashbox;
        this.broughtAll = broughtAll;
        this.other = other;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name = "agent", length = 100)
    public String getAgent() {
        return this.agent;
    }

    public void setAgent(String agent) {
        this.agent = agent;
    }


    @Column(name = "office", length = 100)
    public String getOffice() {
        return this.office;
    }

    public void setOffice(String office) {
        this.office = office;
    }


    @Column(name = "number_office", precision = 5, scale = 0)
    public Integer getNumberOffice() {
        return this.numberOffice;
    }

    public void setNumberOffice(Integer numberOffice) {
        this.numberOffice = numberOffice;
    }


    @Column(name = "area", length = 100)
    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    @Column(name = "creation_date", length = 13)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    @Column(name = "start_date", length = 13)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }


    @Column(name = "first_name", length = 100)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    @Column(name = "last_name", length = 100)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    @Column(name = "patronomic", length = 100)
    public String getPatronomic() {
        return this.patronomic;
    }

    public void setPatronomic(String patronomic) {
        this.patronomic = patronomic;
    }


    @Column(name = "phone_number")
    public Integer getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(Integer phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


    @Column(name = "kind_insurance", length = 100)
    public String getKindInsurance() {
        return this.kindInsurance;
    }

    public void setKindInsurance(String kindInsurance) {
        this.kindInsurance = kindInsurance;
    }


    @Column(name = "base_rate", precision = 20, scale = 0)
    public BigDecimal getBaseRate() {
        return this.baseRate;
    }

    public void setBaseRate(BigDecimal baseRate) {
        this.baseRate = baseRate;
    }


    @Column(name = "price", precision = 20, scale = 0)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }


    @Column(name = "sale", precision = 20, scale = 0)
    public BigDecimal getSale() {
        return this.sale;
    }

    public void setSale(BigDecimal sale) {
        this.sale = sale;
    }


    @Column(name = "delivery", precision = 20, scale = 0)
    public BigDecimal getDelivery() {
        return this.delivery;
    }

    public void setDelivery(BigDecimal delivery) {
        this.delivery = delivery;
    }


    @Column(name = "total_amount", precision = 20, scale = 0)
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }


    @Column(name = "kv", precision = 20, scale = 0)
    public BigDecimal getKv() {
        return this.kv;
    }

    public void setKv(BigDecimal kv) {
        this.kv = kv;
    }


    @Column(name = "kv_all", precision = 20, scale = 0)
    public BigDecimal getKvAll() {
        return this.kvAll;
    }

    public void setKvAll(BigDecimal kvAll) {
        this.kvAll = kvAll;
    }


    @Column(name = "kv_total", precision = 20, scale = 0)
    public BigDecimal getKvTotal() {
        return this.kvTotal;
    }

    public void setKvTotal(BigDecimal kvTotal) {
        this.kvTotal = kvTotal;
    }


    @Column(name = "dk", precision = 20, scale = 0)
    public BigDecimal getDk() {
        return this.dk;
    }

    public void setDk(BigDecimal dk) {
        this.dk = dk;
    }


    @Column(name = "admin_salary", precision = 20, scale = 0)
    public BigDecimal getAdminSalary() {
        return this.adminSalary;
    }

    public void setAdminSalary(BigDecimal adminSalary) {
        this.adminSalary = adminSalary;
    }


    @Column(name = "our_salasy", precision = 20, scale = 0)
    public BigDecimal getOurSalasy() {
        return this.ourSalasy;
    }

    public void setOurSalasy(BigDecimal ourSalasy) {
        this.ourSalasy = ourSalasy;
    }


    @Column(name = "cashbox", precision = 20, scale = 0)
    public BigDecimal getCashbox() {
        return this.cashbox;
    }

    public void setCashbox(BigDecimal cashbox) {
        this.cashbox = cashbox;
    }


    @Column(name = "brought_all", precision = 20, scale = 0)
    public BigDecimal getBroughtAll() {
        return this.broughtAll;
    }

    public void setBroughtAll(BigDecimal broughtAll) {
        this.broughtAll = broughtAll;
    }


    @Column(name = "other", length = 300)
    public String getOther() {
        return this.other;
    }

    public void setOther(String other) {
        this.other = other;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof Osago)) return false;
        Osago castOther = (Osago) other;

        if (((this.getId() == castOther.getId() && this.getId() == null))) {
            return super.equals(other);
        }

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());


        return result;
    }


}


